#!/usr/bin/env tsx
/**
 * Autopilot Loop: Observe → Plan → Apply-Safe → Verify
 * 
 * This script runs periodically to:
 * 1. Observe system state
 * 2. Identify issues or improvements
 * 3. Generate fix/improvement plan
 * 4. Create PR (never direct push)
 * 5. Run tests + deploy to staging
 * 6. Generate evidence pack
 */

import { execSync } from 'child_process';
import { writeFileSync, readFileSync } from 'fs';
import { join } from 'path';

interface SystemState {
  timestamp: string;
  ci_status: 'passing' | 'failing';
  deployed_services: string[];
  error_rate: number;
  performance_p95: number;
  security_alerts: number;
  contract_synced: boolean;
}

interface ChangePlan {
  type: 'fix' | 'improvement' | 'security';
  description: string;
  risk: 'low' | 'medium' | 'high';
  files_to_change: string[];
  tests_to_add: string[];
}

const KILL_SWITCH_FILE = join(__dirname, '../.autopilot-kill-switch');
const SAFE_MODE_FILE = join(__dirname, '../.autopilot-safe-mode');

function checkKillSwitch(): boolean {
  try {
    readFileSync(KILL_SWITCH_FILE);
    console.log('🛑 KILL SWITCH ACTIVE - Autopilot disabled');
    return true;
  } catch {
    return false;
  }
}

function isSafeMode(): boolean {
  try {
    readFileSync(SAFE_MODE_FILE);
    console.log('👀 SAFE MODE - Observe only, no changes');
    return true;
  } catch {
    return false;
  }
}

async function observe(): Promise<SystemState> {
  console.log('📊 Observing system state...');
  
  // Check CI status
  const ciStatus = execSync('gh run list --limit 1 --json conclusion')
    .toString()
    .includes('success') ? 'passing' : 'failing';

  // Check deployed services
  const services = execSync(
    'gcloud run services list --region=us-east1 --format="value(name)"',
    { encoding: 'utf-8' }
  ).trim().split('\n').filter(Boolean);

  // Check contract sync (placeholder - would call actual API)
  const contractSynced = true; // TODO: Implement actual check

  return {
    timestamp: new Date().toISOString(),
    ci_status: ciStatus,
    deployed_services: services,
    error_rate: 0.01, // TODO: Get from monitoring
    performance_p95: 250, // TODO: Get from monitoring
    security_alerts: 0, // TODO: Get from security scanner
    contract_synced: contractSynced
  };
}

async function plan(state: SystemState): Promise<ChangePlan | null> {
  console.log('🧠 Analyzing state and generating plan...');

  // Example: If CI is failing, create fix plan
  if (state.ci_status === 'failing') {
    return {
      type: 'fix',
      description: 'Fix failing CI tests',
      risk: 'low',
      files_to_change: ['apps/api/src/index.ts'],
      tests_to_add: []
    };
  }

  // Example: If error rate is high, create fix plan
  if (state.error_rate > 0.05) {
    return {
      type: 'fix',
      description: 'Reduce error rate',
      risk: 'medium',
      files_to_change: ['apps/api/src/index.ts'],
      tests_to_add: ['apps/api/src/index.test.ts']
    };
  }

  // Example: If security alerts, create security plan
  if (state.security_alerts > 0) {
    return {
      type: 'security',
      description: 'Address security vulnerabilities',
      risk: 'high',
      files_to_change: ['package.json'],
      tests_to_add: []
    };
  }

  console.log('✅ No issues detected');
  return null;
}

async function applySafe(plan: ChangePlan): Promise<string> {
  console.log(`🔧 Applying plan: ${plan.description}`);

  // Create branch
  const branchName = `autopilot/${plan.type}-${Date.now()}`;
  execSync(`git checkout -b ${branchName}`);

  // Make changes (placeholder - would use AI to generate actual changes)
  console.log('Making changes to:', plan.files_to_change);
  
  // Commit
  execSync('git add .');
  execSync(`git commit -m "autopilot: ${plan.description}

Type: ${plan.type}
Risk: ${plan.risk}
Files changed: ${plan.files_to_change.join(', ')}

Generated by Autopilot Loop"`);

  // Push
  execSync(`git push origin ${branchName}`);

  // Create PR
  const prUrl = execSync(
    `gh pr create --title "Autopilot: ${plan.description}" --body "**Type**: ${plan.type}
**Risk**: ${plan.risk}

**Changes**:
${plan.files_to_change.map(f => `- ${f}`).join('\n')}

**Tests**:
${plan.tests_to_add.length > 0 ? plan.tests_to_add.map(t => `- ${t}`).join('\n') : 'No new tests'}

Generated by Autopilot Loop at ${new Date().toISOString()}"`,
    { encoding: 'utf-8' }
  ).trim();

  console.log(`✅ PR created: ${prUrl}`);
  return prUrl;
}

async function verify(prUrl: string): Promise<boolean> {
  console.log('🔍 Verifying changes...');

  // Wait for CI to complete
  console.log('Waiting for CI...');
  execSync('sleep 30'); // Placeholder - would poll CI status

  // Check if tests pass
  const ciPassed = true; // TODO: Check actual CI status

  if (!ciPassed) {
    console.log('❌ CI failed, PR needs manual review');
    return false;
  }

  // Deploy to staging (if tests pass)
  console.log('Deploying to staging...');
  // execSync('./ops/scripts/deploy-staging.sh');

  // Run smoke tests
  console.log('Running smoke tests...');
  // execSync('./ops/scripts/verify.sh staging');

  console.log('✅ Verification complete');
  return true;
}

async function generateEvidencePack(state: SystemState, plan: ChangePlan | null, prUrl?: string) {
  const report = `# Autopilot Run Evidence Pack

**Timestamp**: ${state.timestamp}

## System State
- CI Status: ${state.ci_status}
- Deployed Services: ${state.deployed_services.join(', ')}
- Error Rate: ${state.error_rate}%
- Performance P95: ${state.performance_p95}ms
- Security Alerts: ${state.security_alerts}
- Contract Synced: ${state.contract_synced ? 'Yes' : 'No'}

## Action Taken
${plan ? `
**Type**: ${plan.type}
**Description**: ${plan.description}
**Risk**: ${plan.risk}
**PR**: ${prUrl || 'N/A'}
` : 'No action needed - system healthy'}

## Next Run
Scheduled for: ${new Date(Date.now() + 3600000).toISOString()}
`;

  const reportPath = join(__dirname, '../reports', `autopilot-${Date.now()}.md`);
  writeFileSync(reportPath, report);
  console.log(`📋 Evidence pack saved: ${reportPath}`);
}

async function main() {
  console.log('🤖 Autopilot Loop Starting...\n');

  // Check kill switch
  if (checkKillSwitch()) {
    process.exit(0);
  }

  const safeMode = isSafeMode();

  try {
    // 1. Observe
    const state = await observe();
    console.log('State:', JSON.stringify(state, null, 2), '\n');

    // 2. Plan
    const plan = await plan(state);
    
    if (!plan) {
      console.log('✅ System healthy, no changes needed\n');
      await generateEvidencePack(state, null);
      return;
    }

    console.log('Plan:', JSON.stringify(plan, null, 2), '\n');

    if (safeMode) {
      console.log('👀 SAFE MODE: Would have created PR, but observing only\n');
      await generateEvidencePack(state, plan);
      return;
    }

    // 3. Apply (create PR)
    const prUrl = await applySafe(plan);

    // 4. Verify
    const verified = await verify(prUrl);

    // 5. Generate evidence
    await generateEvidencePack(state, plan, prUrl);

    console.log('\n✅ Autopilot loop complete');
  } catch (error) {
    console.error('❌ Autopilot error:', error);
    process.exit(1);
  }
}

main();
